title: Planet Environment Status
languageCode: en
params:
  copyrightHolder: 'Planet [Redacted]'
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: ''
  description_header: Status updates about our planet.
  eventsPerPage: 10
  logo: ''
  meta_description: >-
    This status page provides updated information about our planet's
    environmental condition.
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - name: Main Planet Condition
  timezoneString: CST
